
* Multi-n-Back

** Introduction
   A simple web n-back implementation. Used to train working memory.
   This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.4.9.

** References
   [[https://link.springer.com/article/10.1007/s41465-017-0044-1][N-back versus complex span working memory test]]

** Angular-cli notes
*** Development server
    Run `ng serve` for a dev server. Navigate to `http://localhost:4200/`.

*** Code scaffolding
    Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

*** Build
    Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `-prod` flag for a production build.

*** Running unit tests
  Run `ng test` to execute the unit tests via [Karma](https://karma-runner.github.io).

*** Running end-to-end tests
  Run `ng e2e` to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).
